apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.example2HelmBasic.namespace }}
  name: example2-helm-basic
  labels:
    app: example2-helm-basic
    app.kubernetes.io/part-of: example2-helm-basic
    tenant: {{ .Values.tenant.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example2-helm-basic
  template:
    metadata:
      labels:
        app: example2-helm-basic
        tenant: {{ .Values.tenant.name }}
    spec:
      containers:
      - name: example2-helm-basic
        image: registry.access.redhat.com/ubi8/httpd-24:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http

        volumeMounts:
        - name: html-content
          mountPath: /var/www/html
          readOnly: true

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

      volumes:
      - name: html-content
        configMap:
          name: example2-html
