apiVersion: vlic.veritas.com/v1
kind: License
metadata:
  name: license-dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  licenseEdition: Enterprise
