apiVersion: infoscale.veritas.com/v1
kind: InfoScaleCluster
metadata:
  name: cluster-prod
  namespace: infoscale-vtas
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encrypted: false
  sameEncKey: false
  enableScsi3pr: false
  isSharedStorage: true
  version: 9.1.2
  clusterInfo:
  - nodeName: {{ index .Values.allNodeNames 1 | quote }}
    excludeDevice:
    - "/dev/disk/by-path/pci-0000:08:00.0"
