apiVersion: infoscale.veritas.com/v1
kind: InfoScaleCluster
metadata:
  name: cluster-prod
  namespace: infoscale-vtas
spec:
  encrypted: false
  clusterInfo:
    - nodeName: {{ .Values.nodeName | quote }}
      excludeDevice:
      - "/dev/disk/by-path/pci-0000:08:00.0"
  sameEncKey: false
  enableScsi3pr: false
  isSharedStorage: true
  version: 9.1.2
