kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: infoscale-rootdisk-sc
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: org.veritas.infoscale
parameters:
  layout: concat
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
