{{- if eq (.Values.nodeIndex | int) 1 }}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: openmrs01
  namespace: openmrs
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: openmrs01
spec:
  runStrategy: RerunOnFailure
  dataVolumeTemplates:
    - metadata:
        name: openmrs-rootdisk
      spec:
        source:
          http:
            url: https://axjfkoyyx3u5.objectstorage.us-phoenix-1.oci.customer-oci.com/p/iTzjUCukiS0c54JxKE-T0LzcdD_WoWB0Y-1psgaWPwN7Vg7DqG8NK24tK0KaFSiF/n/axjfkoyyx3u5/b/rhelsummit/o/vmopenmrs01.qcow2
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: infoscale-rootdisk-sc
  template:
    metadata:
      labels:
        kubevirt.io/domain: openmrs01
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 4
          threads: 1
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
          rng: {}
        memory:
          guest: 8Gi
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          dataVolume:
            name: openmrs-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: ev0t-55ur-w8xw
              chpasswd: { expire: False }
{{- end }}