apiVersion: infoscale.veritas.com/v1
kind: InfoScaleCluster
metadata:
  name: cluster-prod
  namespace: infoscale-vtas
spec:
  encrypted: false
  clusterInfo:
    - nodeName: ocpprod01.ocp01.arctera.local
  sameEncKey: false
  enableScsi3pr: false
  isSharedStorage: true
  version: 9.1.2

