apiVersion: v1
kind: Namespace
metadata:
  name: infoscale-vtas
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: infoscale-vtas-og
  namespace: infoscale-vtas
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: infoscale-licensing-operator
  namespace: infoscale-vtas
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  channel: fast
  name: infoscale-licensing-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: infoscale-sds-operator
  namespace: infoscale-vtas
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  channel: fast
  name: infoscale-sds-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
