---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-lookup-job
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-lookup-job
  annotations:
    argocd.argoproj.io/sync-wave: "3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: node-lookup-job
  namespace: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: node-lookup-job
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: node-lookup-job
      containers:
      - name: node-lookup-job
        image: bitnami/kubectl:latest
        #image: image-registry.openshift-image-registry.svc:5000/openshift/cli
        command:
        - /bin/sh
        - -c
        - |
          NODES=$(kubectl get nodes -o jsonpath='{.items[*].metadata.name}')
          COMMAND="kubectl create configmap node-list-config -n openshift-gitops --dry-run=client -o yaml"

          for node in $NODES; do
            COMMAND="$COMMAND --from-literal=$node=active"
          done

          $COMMAND | kubectl apply -f -
