---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-lookup-job
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-lookup-job
  annotations:
    argocd.argoproj.io/sync-wave: "3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: node-lookup-job
  namespace: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: node-lookup-job
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: node-lookup-job
      containers:
      - name: node-lookup-job
        image: image-registry.openshift-image-registry.svc:5000/openshift/cli
        command:
        - /bin/sh
        - -c
        - |
          NODES=$(oc get nodes -o jsonpath='{.items[*].metadata.name}' | tr ' ' ',')
          oc create configmap node-list-config --from-literal=nodeList=$NODES \
            -n default --dry-run=client -o yaml | oc apply -f -
