apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: infoscale-rootdisk-sc
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  claimPropertySets:
    - accessModes:
        - ReadWriteMany
      volumeMode: Block
    - accessModes:
        - ReadWriteOnce
      volumeMode: Block
    - accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
    - accessModes:
        - ReadWriteMany
      volumeMode: Filesystem
